# Generated by Django 4.2.7 on 2025-12-15 13:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('business_units', '0003_alter_businessunit_api_key'),
        ('go_guide_portal', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='businessunituser',
            options={'verbose_name': 'Пользователь площадки', 'verbose_name_plural': 'Пользователи площадок'},
        ),
        migrations.AlterModelOptions(
            name='knowledgefile',
            options={'verbose_name': 'Файл базы знаний', 'verbose_name_plural': 'Файлы базы знаний'},
        ),
        migrations.AlterField(
            model_name='businessunituser',
            name='business_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business_units.businessunit', verbose_name='Площадка'),
        ),
        migrations.AlterField(
            model_name='businessunituser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='knowledgefile',
            name='business_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_files', to='business_units.businessunit', verbose_name='Площадка'),
        ),
        migrations.AlterField(
            model_name='knowledgefile',
            name='content_hash',
            field=models.CharField(max_length=64, verbose_name='Хэш содержимого'),
        ),
        migrations.AlterField(
            model_name='knowledgefile',
            name='filename',
            field=models.CharField(max_length=255, verbose_name='Имя файла'),
        ),
        migrations.AlterField(
            model_name='knowledgefile',
            name='uploaded_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Загружен'),
        ),
    ]
