# Generated by Django 4.2.7 on 2025-12-15 16:54

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('business_units', '0004_businessunit_alice_key_businessunit_gigachat_key_and_more'),
        ('go_guide_portal', '0002_alter_businessunituser_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='ai_knowledge/', verbose_name='Файл')),
                ('original_name', models.CharField(max_length=255, verbose_name='Имя файла')),
                ('status', models.CharField(choices=[('pending', 'Ожидает обработки'), ('processed', 'Обработан'), ('failed', 'Ошибка')], default='pending', max_length=20, verbose_name='Статус')),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Загружен')),
                ('business_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_documents', to='business_units.businessunit', verbose_name='Площадка')),
            ],
            options={
                'verbose_name': 'Документ базы знаний',
                'verbose_name_plural': 'Документы базы знаний',
            },
        ),
    ]
