# Generated by Django 4.2.7 on 2025-12-20 06:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('go_guide_portal', '0003_knowledgedocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgedocument',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_documents', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='knowledgedocument',
            name='file',
            field=models.FileField(upload_to='knowledge/%Y/%m/%d/', verbose_name='Файл'),
        ),
    ]
