# Generated by Django 4.2.7 on 2025-12-20 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('go_guide_portal', '0004_knowledgedocument_user_alter_knowledgedocument_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='knowledgefile',
            name='business_unit',
        ),
        migrations.DeleteModel(
            name='KnowledgeDocument',
        ),
        migrations.DeleteModel(
            name='KnowledgeFile',
        ),
    ]
