# Generated by Django 4.2.7 on 2025-12-15 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='service_type',
            field=models.CharField(blank=True, choices=[('Люкс', 'Люкс'), ('Комфорт', 'Комфорт'), ('Стандарт', 'Стандарт'), ('Эконом', 'Эконом')], default='Стандарт', max_length=255, verbose_name='Тип услуги'),
        ),
    ]
