# Generated by Django 4.2.7 on 2025-12-15 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('slug', models.SlugField(unique=True, verbose_name='Слаг')),
                ('api_key', models.CharField(default='a29a32b442bd0e75ff7b3acbf58c1c0d6385a4a68ee41cb28c21b6839550f172', max_length=64, unique=True, verbose_name='API ключ')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Адрес')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('photo_url', models.URLField(blank=True, null=True, verbose_name='URL фото')),
            ],
            options={
                'verbose_name': 'Площадка/Бизнес',
                'verbose_name_plural': 'Площадки/Бизнесы',
            },
        ),
    ]
