# Generated by Django 4.2.7 on 2025-12-15 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_units', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessunit',
            name='business_type',
            field=models.CharField(choices=[('hotel', 'Отели / Хостелы'), ('service', 'Услуги (салон, СТО, врач)'), ('tour', 'Туры / Экскурсии'), ('event', 'Мероприятия / Билеты'), ('rent', 'Аренда (авто, инвентарь)')], default='service', max_length=20, verbose_name='Тип бизнеса'),
        ),
        migrations.AlterField(
            model_name='businessunit',
            name='api_key',
            field=models.CharField(default='fe96ee1ace99adc116b6eac9b5b9e1bd5934af3be69e3386ce40453b47609918', max_length=64, unique=True, verbose_name='API ключ'),
        ),
    ]
