# Generated by Django 4.2.7 on 2025-12-15 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_units', '0002_businessunit_business_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessunit',
            name='api_key',
            field=models.CharField(default='f9c840fd1909dab8a56ec98a8eeed2adb4c26e3280f102a022e079df54463147', max_length=64, unique=True, verbose_name='API ключ'),
        ),
    ]
