# Generated by Django 4.2.7 on 2025-12-15 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_units', '0003_alter_businessunit_api_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessunit',
            name='alice_key',
            field=models.TextField(blank=True, null=True, verbose_name='Yandex Alice API Key'),
        ),
        migrations.AddField(
            model_name='businessunit',
            name='gigachat_key',
            field=models.TextField(blank=True, null=True, verbose_name='GigaChat Auth Key'),
        ),
        migrations.AlterField(
            model_name='businessunit',
            name='api_key',
            field=models.CharField(default='7f7eea1323149b89777acd4d692b6d638bba829143b8016034ffe9a653000c86', max_length=64, unique=True, verbose_name='API ключ'),
        ),
    ]
