# Generated by Django 4.2.7 on 2025-12-15 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_units', '0004_businessunit_alice_key_businessunit_gigachat_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessunit',
            name='gigachat_auth_key',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Gigachat Auth Key'),
        ),
        migrations.AlterField(
            model_name='businessunit',
            name='api_key',
            field=models.CharField(default='0df47ead79f7dd60113f92d75d5e3ad887e4bc7450dd316f36e470abd76af422', max_length=64, unique=True, verbose_name='API ключ'),
        ),
    ]
