# Generated by Django 4.2.7 on 2025-12-16 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_units', '0005_businessunit_gigachat_auth_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessunit',
            name='gigachat_client_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='GigaChat Client ID'),
        ),
        migrations.AlterField(
            model_name='businessunit',
            name='api_key',
            field=models.CharField(default='a1e5e24b0c14bed985feca7c0a6e2583a4f9c1eb5fb2db5c442dd68e015de0f0', max_length=64, unique=True, verbose_name='API ключ'),
        ),
        migrations.AlterField(
            model_name='businessunit',
            name='gigachat_auth_key',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='GigaChat Authorization Key (secret)'),
        ),
    ]
