# Generated by Django 4.2.7 on 2025-12-16 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_units', '0006_businessunit_gigachat_client_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessunit',
            name='gigachat_scope',
            field=models.CharField(blank=True, default='GIGACHAT_API_PERS', max_length=64, null=True, verbose_name='GigaChat Scope'),
        ),
        migrations.AlterField(
            model_name='businessunit',
            name='api_key',
            field=models.CharField(default='cee2f7ed9b0d2787a0013a0173757b52ce3a73d020ac36867e414d742fd30e6e', max_length=64, unique=True, verbose_name='API ключ'),
        ),
        migrations.AlterField(
            model_name='businessunit',
            name='gigachat_auth_key',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='GigaChat Authorization Key (secret)'),
        ),
    ]
