# Generated by Django 4.2.7 on 2025-12-20 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_units', '0007_businessunit_gigachat_scope_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessunit',
            name='phone',
            field=models.CharField(blank=True, max_length=32, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='businessunit',
            name='api_key',
            field=models.CharField(default='29bcde3f84c7e1b33ff38fe0f30e0b35c8842f7e1d2c8a549f7972bc17c89161', max_length=64, unique=True, verbose_name='API ключ'),
        ),
    ]
