# Generated by Django 4.2.7 on 2025-12-20 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_units', '0008_businessunit_phone_alter_businessunit_api_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessunit',
            name='accessibility',
            field=models.CharField(blank=True, max_length=255, verbose_name='Доступность/инклюзивность'),
        ),
        migrations.AddField(
            model_name='businessunit',
            name='allow_emoji',
            field=models.BooleanField(default=True, verbose_name='Разрешать эмодзи в ответах ассистента'),
        ),
        migrations.AddField(
            model_name='businessunit',
            name='checkin_time',
            field=models.CharField(blank=True, max_length=16, verbose_name='Чек-ин'),
        ),
        migrations.AddField(
            model_name='businessunit',
            name='checkout_time',
            field=models.CharField(blank=True, max_length=16, verbose_name='Чек-аут'),
        ),
        migrations.AddField(
            model_name='businessunit',
            name='coordinates',
            field=models.CharField(blank=True, max_length=255, verbose_name='Координаты/проезд'),
        ),
        migrations.AddField(
            model_name='businessunit',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='E-mail'),
        ),
        migrations.AddField(
            model_name='businessunit',
            name='kids_policy',
            field=models.CharField(blank=True, max_length=255, verbose_name='Детская политика/опции'),
        ),
        migrations.AddField(
            model_name='businessunit',
            name='meals_info',
            field=models.CharField(blank=True, max_length=255, verbose_name='Питание'),
        ),
        migrations.AddField(
            model_name='businessunit',
            name='parking_info',
            field=models.CharField(blank=True, max_length=255, verbose_name='Парковка'),
        ),
        migrations.AddField(
            model_name='businessunit',
            name='pets_policy',
            field=models.CharField(blank=True, max_length=255, verbose_name='Политика по питомцам'),
        ),
        migrations.AddField(
            model_name='businessunit',
            name='positioning',
            field=models.TextField(blank=True, verbose_name='УТП/позиционирование'),
        ),
        migrations.AddField(
            model_name='businessunit',
            name='smoke_policy',
            field=models.CharField(blank=True, max_length=255, verbose_name='Политика курения'),
        ),
        migrations.AddField(
            model_name='businessunit',
            name='socials',
            field=models.TextField(blank=True, verbose_name='Соцсети/ссылки'),
        ),
        migrations.AddField(
            model_name='businessunit',
            name='tone',
            field=models.CharField(choices=[('friendly', 'Дружелюбный'), ('neutral', 'Нейтральный'), ('formal', 'Строгий')], default='friendly', max_length=16, verbose_name='Тон ассистента'),
        ),
        migrations.AddField(
            model_name='businessunit',
            name='website',
            field=models.URLField(blank=True, verbose_name='Сайт'),
        ),
        migrations.AddField(
            model_name='businessunit',
            name='wifi_info',
            field=models.CharField(blank=True, max_length=255, verbose_name='Wi‑Fi'),
        ),
        migrations.AddField(
            model_name='businessunit',
            name='working_hours_from',
            field=models.CharField(blank=True, max_length=16, verbose_name='Время открытия'),
        ),
        migrations.AddField(
            model_name='businessunit',
            name='working_hours_to',
            field=models.CharField(blank=True, max_length=16, verbose_name='Время закрытия'),
        ),
        migrations.AlterField(
            model_name='businessunit',
            name='api_key',
            field=models.CharField(default='1de9dd489437ef75673a087853ed39e2f69a92353e599f46342ecf2c155eb5fd', max_length=64, unique=True, verbose_name='API ключ'),
        ),
    ]
