# Generated by Django 4.2.7 on 2025-12-20 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_units', '0009_businessunit_accessibility_businessunit_allow_emoji_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessunit',
            name='api_key',
            field=models.CharField(default='f1c4c808476bec6c40daae1e90d7d4a7f3f876a8b453613a04ec2664e579d1bc', max_length=64, unique=True, verbose_name='API ключ'),
        ),
    ]
